urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^catalogue/', include('myLibrary.catalogue.urls')),
    ('', include('myLibrary.web.urls')),

    # (r'^openid/$', 'django_openidconsumer.views.begin', { 'sreg': 'nickname' }),
    # (r'^openid/complete/$', 'django_openidconsumer.views.complete'),
    # (r'^openid/signout/$', 'django_openidconsumer.views.signout'),

    ('^accounts/login/?$', 'django.contrib.auth.views.login'),
    ('^accounts/logout/?$', 'django.contrib.auth.views.logout'),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
)

if settings.SERVE_MEDIA:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

urlpatterns += patterns('',
    ('^(?P<what>.*)$', 'views.bad')
)

catalogue/models.py
from django.db import models

class BookFormat(models.Model):
    """
    Book format
    """
    name = models.CharField(max_length=128, null=False, unique=True)

    def __unicode__(self):
        return self.name

class Author(models.Model):
    """
    Author record
    """

    name = models.CharField(max_length=256, null=False, unique=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']

class Tag(models.Model):
    """
    Tag record
    """

    name = models.CharField(max_length=128, null=False)
    parent = models.ForeignKey('self', null=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']
        unique_together = (
            ('name', 'parent'),
        )

class Series(models.Model):
    """
    Series information
    """
    name = models.CharField(max_length=256, null=False)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Series'
        db_table = 'catalogue_series'
        ordering = ['name']

class Book(models.Model):
    """
    Book record
    """

    uid = models.CharField(max_length=1024, null=False)
    uid_scheme = models.CharField(max_length=64, null=False)

    title = models.TextField(null=False)
    authors = models.ManyToManyField(Author, through='BookAuthor')
    series = models.ManyToManyField(Series, through='BookSeries')
    tags = models.ManyToManyField(Tag, through='BookTag')

    language = models.CharField(max_length=64, null=False)

    # MSS: probably, this needs to be replaced with FileField or something
    file = models.TextField(null=False)
    file_stamp = models.DateTimeField()

    mimetype = models.CharField(max_length=128, null=False)

    format = models.ForeignKey(BookFormat, null=False)

    annotation = models.TextField(null=True)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['title']
        unique_together = (
            ('uid', 'uid_scheme'),
        )

class BookAuthor(models.Model):
    """
    Link between books and authors
    """

    book = models.ForeignKey(Book)
    author = models.ForeignKey(Author)
    position = models.PositiveIntegerField(null=False)

    class Meta:
        unique_together = (
            ('book', 'author'),
        )
        ordering = ['position']

class BookSeries(models.Model):
    """
    Link between books and series
    """

    book = models.ForeignKey(Book)
    series = models.ForeignKey(Series)
    number = models.IntegerField()

    class Meta:
        unique_together = (
            ('book', 'series', 'number'),
        )

class BookTag(models.Model):
    """
    Link between book and tags
    """

    book = models.ForeignKey(Book)
    tag = models.ForeignKey(Tag)

    class Meta:
        unique_together = (
            ('book', 'tag'),
        )

# vim:ts=4:sw=4:et

templates/about.html
{% extends "base.html" %}

{% block title %}About{% endblock %}
{% block leftsidebar %}{% endblock %}

{% block body%}<h1>Great stuff!</h1>

<p>Really!</p>{% endblock %}

<!--
  vim:ts=2:sw=2:et:filetype=htmldjango
  -->

templates/all-series.html
{% extends "base.html" %}

{% block title %}Series{% endblock %}

{% block breadcrumbs %} &rsaquo; Series{% endblock %}

{% block body %}<h1>Series</h1>
<table border="1">
  <tr>
    <td>Name</td><td>Books</td>
  </tr>
  {% for item in series %}<tr>
    <td><a href="/series/{{ item.id }}">{{ item.name }}</a></td><td>{{ item.bookseries_set.count }}</td>
  </tr>{% endfor %}
</table>
{% endblock %}

<!--
  vim:ts=4:sw=4:et:filetype=htmldjango
  -->

templates/author.html
{% extends "base.html" %}

{% block title %}Author: {{ author.name }}{% endblock %}

{% block body %}<h1>{{ author.name }}</h1>
<table border="0">
  <tr>
    <td>Title</td><td>Download</td>
  </tr>
  {% for book in books %}<tr>
    <td><a href="/book/{{ book.id }}">{{ book.title }}</a></td><td><a href="/file/{{ book.id }}">{{ book.format.name }}</a></td>
  </tr>{% endfor %}
</table>
{% endblock %}

<!--
  vim:ts=2:sw=2:et:filetype=htmldjango
  -->

templates/authors.html
{% extends "base.html" %}

{% block title %}Authors{% endblock %}

{% block breadcrumbs %} &rsaquo; Authors{% endblock %}

{% block body %}<h1>Authors</h1>
<table border="1">
  <tr>
    <td>Name</td><td>Books</td>
  </tr>
  {% for author in authors %}<tr>
    <td><a href="/author/{{ author.id }}">{{ author.name }}</a></td><td>{{ author.bookauthor_set.count }}</td>
  </tr>{% endfor %}
</table>
{% endblock %}

<!--
  vim:ts=4:sw=4:et:filetype=htmldjango
  -->

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="Robots" content="index,follow" />
  <link rel="stylesheet" href="/static/style.css" type="text/css" />
  <title>{% block title %}{{ title }}{% endblock %}</title>
  <link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon" />
  <link rel="icon" href="/static/favicon.ico" type="image/x-icon" />
  {% block head %}{% endblock %}
</head>
<body>
<div id="wrap">
	<div id="header"><div id="header-links">
      <p>{% if USER_ACTION_URL %}{% if USER_NAME %}Logged as: {{ USER_NAME }} | <a href="/profile">Profile</a> | <a href="{{ USER_ACTION_URL }}">Log out</a>{% else %}Not logged in | <a href="{{ USER_ACTION_URL }}">Log in</a>{% endif %}{% else %}<font color="red">NO USER DATA!</font>{% endif %}</p>
  </div></div>

	<div id="header-photo">
		<h1 id="logo-text"><a href="/" title="">{{ SITE_TITLE }}</a></h1>
		<h2 id="slogan">{{ SITE_SUBTITLE }}</h2>
	</div>
	<div id="nav">
    {% if MAIN_MENU %}<ul>
    {% for item in MAIN_MENU %}  <li><a href="{{ item.1 }}">{{ item.0 }}</a></li>
    {% endfor %}</ul>{% else %}<font color="red">MAIN_MENU is not defined</font>{% endif %}
	</div>

	<div id="content-wrap" class="three-col">
		<div id="sidebar">{% block leftsidebar %}{% endblock %}</div>
		<div id="rightcolumn">{% block rightsidebar %}<h1>Search Books</h1>
    <form action="/search" class="searchform">
				<p><input name="search_query" class="textbox" type="text" />
  				<input name="search" class="button" value="Go" type="submit" /></p>
			</form>{% endblock %}</div>
		<div id="main">{% block body %}{{ body }}{% endblock %}</div>
	</div>

	<div id="footer-wrap"><div id="footer">{% block footer %}
			<p><a href="/about">About</a> | <a href="/feedback">Feedback</a><br/>&copy; 2008 <strong>{{ COMPANY }}</strong> | Design by: <a href="http://www.styleshout.com/">styleshout</a></p>
	{% endblock %}</div></div>
</div>
</body>
</html>

<!--
  vim:ts=2:sw=2:et:filetype=htmldjango
  -->

templates/book.html
{% extends "base.html" %}

{% block title %}Book: {{ book.title }}{% endblock %}

{% block leftsidebar %}<h1>Book Info</h1>
<div>
    <b>Language</b>: {{ book.language }}
</div>
{% if book.bookseries_set.all.count %}<div><b>Series</b>:<ul>{% for series in book.bookseries_set.all %}
    <li><a href="/series/{{ series.series.id}}">{{ series.series.name }}</a> (#{{ series.number }})</li>{% endfor %}
</ul></div>{% endif %}
{% if tags %}<div><b>Tags</b>: <ul>{% for tag in tags %}
    <li><a href="/tag/{{ tag.id }}">{{ tag.name }}</a></li>{% endfor %}
</ul></div>{% endif %}
<div><b>Download</b>: <a href="/file/{{ book.id }}">{{ book.format.name }}</a></div>
{% endblock %}

{% block body %}<h1>{{ book.title }}</h1>
<p>by {% for author in authors %}{% if not forloop.first %}, {% endif %}<a href="/author/{{ author.id }}">{{ author.name }}</a>{% endfor %}</p>
{% if book.annotation %}<h2>Annotation</h2><p>{{ book.annotation }}</p>{% endif %}
{% endblock %}

<!--
  vim:ts=4:sw=4:et:filetype=htmldjango
  -->

templates/books.html
{% extends "base.html" %}

{% block title %}Books{% endblock %}

{% block breadcrumbs %} &rsaquo; Books{% endblock %}

{% block body %}<h1>Books</h1>
<table border="0">
  <tr>
    <td>Title</td><td>Download</td>
  </tr>
  {% for book in books %}<tr>
    <td><a href="/book/{{ book.id }}">{{ book.title }}</a></td><td><a href="/file/{{ book.id }}"><img src="/static/download.png" alt="download"/></a></td>
  </tr>{% endfor %}
</table>
{% endblock %}

<!--
  vim:ts=4:sw=4:et:filetype=htmldjango
  -->

templates/feedback.html
{% extends "base.html" %}

{% block title %}Feedback Form{% endblock %}
{% block body %}The feedback form will be added shortly{% endblock %}

<!--
  vim:ts=4:sw=4:et:filetype=htmldjango
  -->

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block body %}Welcome to the library!{% endblock %}

<!--
  vim:ts=4:sw=4:et:filetype=htmldjango
  -->

templates/series.html
{% extends "base.html" %}

{% block title %}Series: {{ series.name }}{% endblock %}

{% block body %}<h1>{{ series.name }}</h1>
<table border="0">
  <tr>
    <td>Position</td><td>Title</td>
  </tr>
  {% for book in books %}<tr>
    <td>{{ book.0 }}<td><a href="/file/{{ book.1.id }}"><img src="/static/download.png" alt="download"/></a><a href="/book/{{ book.1.id }}">{{ book.1.title }}</a></td>
  </tr>{% endfor %}
</table>
{% endblock %}

<!--
  vim:ts=2:sw=2:et:filetype=htmldjango
  -->

templates/tag.html
{% extends "base.html" %}

{% block title %}Tag: {{ author.name }}{% endblock %}

{% block breadcrumbs %} &rsaquo; <a href="/tag">Tags</a> &rsaquo; {% for parent in tag_path %}<a href="/tag/{{ parent.id }}">{{ parent.name }}</a> &rsaquo; {% endfor %}{{ tag }}{% endblock %}

{% block body %}<h1>{{ tag }}</h1>
{% if subtags %}<h2>Sub-tags</h2>
<table border="1">
  <tr>
    <td>Name</td><td>Books</td><td>Subtags</td>
  </tr>
  {% for subtag in subtags %}<tr>
    <td><a href="/tag/{{ subtag.0 }}">{{ subtag.1 }}</a></td><td>{{ subtag.2 }}</td><td>{{ subtag.3 }}</td>
  </tr>{% endfor %}
</table>{% endif %}

{% if books %}<h2>Books</h2>
<table border="1">
  <tr>
    <td>Title</td><td>Download</td>
  </tr>
  {% for book in books %}<tr>
    <td><a href="/book/{{ book.id }}">{{ book.title }}</a></td><td><a href="/file/{{ book.id }}"><img src="/static/download.png" alt="download"/></a></td>
  </tr>{% endfor %}
</table>{% endif %}
{% endblock %}

<!--
  vim:ts=2:sw=2:et:filetype=htmldjango
  -->

templates/tags.html
{% extends "base.html" %}

{% block title %}Tags{% endblock %}

{% block breadcrumbs %} &rsaquo; Tags{% endblock %}

{% block body %}<h1>Tags</h1>
<table border="1">
  <tr>
    <td>Name</td><td>Books</td><td>Subtags</td>
  </tr>
  {% for tag in tags %}<tr>
    <td><a href="/tag/{{ tag.0 }}">{{ tag.1 }}</a></td><td>{{ tag.2 }}</td><td>{{ tag.3 }}</td>
  </tr>{% endfor %}
</table>
{% endblock %}

<!--
  vim:ts=4:sw=4:et:filetype=htmldjango
  -->